projects:
  app:
    schemaPath: "appmodel.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
